### ISSUE TITLE
Input placeholder has weird placements

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#679] opened 2020-03-03 19:09 UTC
![Screenshot from 2020-03-03 16-06-52](https://user-images.githubusercontent.com/43217/75810273-0f6d6c00-5d69-11ea-8cdd-ee6b0a4e1871.png)

Once a value is inserted, value is properly aligned.

**Comment by Velenir** [comment] 2020-03-04 08:05
Where can I see this? Can't reproduce right away

**Comment by W3stside** [comment] 2020-03-04 10:01
it's the placeholder value - honestly no idea in the CSS why it happens, quick fix would be no placeholder

**Comment by alfetopito** [comment] 2020-03-04 11:17
> Where can I see this? Can't reproduce right away

On `Balances` page, click on `deposit` or `withdraw`. The values starts that way.

I'm using Firefox BTW.

**Comment by W3stside** [comment] 2020-03-12 13:49
Closed by #711

**Closed** 2020-03-12 15:59 UTC
Labels: bug
