### ISSUE TITLE
Integrate contextual tooltips for helpers

### ISSUE THREAD

**Issue by Velenir** [gnosis/dex-react#476] opened 2020-01-31 09:19 UTC
- Explore library options for tooltips.
- Add sample integration somewhere
- Don't actually add many tooltips before new design is ready

Library candidates: https://popper.js.org/

**Estimation: ~~2~~ 3.5**

### Update

New requirement: fill in all texts (estimation updated to reflect it)

### Dependencies

Task to get texts https://github.com/gnosis/dex-react/issues/533

**Comment by alfetopito** [comment] 2020-02-13 12:32
Duplicate of https://github.com/gnosis/dex-react/issues/174

**Closed** 2020-02-27 10:55 UTC
