### ISSUE TITLE
Make withdraw/claiming process more clear

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#827] opened 2020-04-03 20:22 UTC
Right now:

1. You withdraw, an spinner is shown

![image](https://user-images.githubusercontent.com/2352112/78401459-118d4980-75f9-11ea-9b44-f8a8af95e467.png)

2. Once the tx is mined, it shows that we need to wait for the next batch
![image](https://user-images.githubusercontent.com/2352112/78401600-67fa8800-75f9-11ea-8479-4b680b8f5209.png)

3. Ready to claim!
![image](https://user-images.githubusercontent.com/2352112/78401621-734db380-75f9-11ea-9442-9a4b2626bd65.png)

-------------

## Proposals for improvements

**A. Add some descriptive message in the modal**
Before we initiate the withdraw/claim process, just a small description of the process would be nice:
- Saying it's a 2 step process
- A short explanation on why there's 2 steps, probably with an extended description in the FAQ (so a link there)

![image](https://user-images.githubusercontent.com/2352112/78401693-9d9f7100-75f9-11ea-9049-c4271a02b114.png)

**B. Countdown** 
In step **2.** I think it's nice to replace the icon by a message with a countdown “Claimable in 3min 59s”

**C. Tooltips in the titles** 
![image](https://user-images.githubusercontent.com/2352112/78402158-6b424380-75fa-11ea-9a31-c63734ee51f3.png)

Probably a good idea to add a tooltip. Specially for the "Pending Withdrawals" we could link to the FAQ mentioned in **B.**

**Comment by alfetopito** [comment] 2020-07-07 18:06
This has been half implemented.
There's is a warning and a mention to FAQ, but there's no FAQ entry.

A new task has been created to address that.

I would say what's left now is a duplicate of #1148 

Closing in favor of the new task.

**Closed by alfetopito** 2020-07-07 18:06 UTC
