### ISSUE TITLE
Issue with useTokenHook, Rinkeby, and default web3 connection

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#875] opened 2020-04-09 18:37 UTC
Yep, we all know about this weird error that we try to get info from tokens of Mainnet but in Rinkeby network.

Not sure, but likely it was introduced here. Although it seems strange by the changes in the commit: https://github.com/gnosis/dex-react/pull/780/commits/b79ff1a044d5fc4c813e3d6c81888a2d85ffd939

Need more investigation

**Comment by alfetopito** [comment] 2020-04-09 20:18
Printing from this `useEffect` hook https://github.com/gnosis/dex-react/blob/develop/src/hooks/useTokenBalances.ts#L119
The current networkId and the tokens for given network id.
Tested on latest `develop` aabbbde2ceb9658557de71925a02a249917e92f7

When not connected, default is mainnet, everything is fine:
![screenshot_2020-04-09_13-08-19](https://user-images.githubusercontent.com/43217/78936666-e0cb6b00-7a63-11ea-9188-ef8110be307e.png)

Connecting MM on rinkeby, the network id changes, but not yet the tokens:
![screenshot_2020-04-09_13-09-28](https://user-images.githubusercontent.com/43217/78936717-f80a5880-7a63-11ea-9fc0-872e128066ac.png)

Then the query to update the balances is triggered, using the new networkId but the old list of tokens:
![screenshot_2020-04-09_13-09-59](https://user-images.githubusercontent.com/43217/78936777-15d7bd80-7a64-11ea-9af1-043682eb9272.png)

Old networkId/token addresses combo promises are still going on the background, while the list of tokens is updated:
![screenshot_2020-04-09_13-10-17](https://user-images.githubusercontent.com/43217/78936836-2ee06e80-7a64-11ea-8b87-a58a5b514bf8.png)

Now all tokens are fine...

**Comment by alfetopito** [comment] 2020-04-09 20:24
Seems like the issue is, now that `tokenList` is dynamic and is updated async, it needs an extra hop when networkId is updated.
Since the `useEffect` hook depends on both `networkId` and `tokens`, it'll trigger two updates once networkId changes.

Instead, we should only update when tokens change. Otherwise we'll have a list of tokens not matching the networkId.

**Comment by alfetopito** [comment] 2020-04-09 22:35
Attempt to fix it here #877

If that's not a good solution, another alternative that I considered but did not implement is to include networkId as part of `getTokens` response, or even part of `TokenDetails` interface ...

**Comment by alfetopito** [comment] 2020-04-10 16:23
Alternative fix by @Velenir that actually fixes it https://github.com/gnosis/dex-react/pull/878

**Comment by Velenir** [comment] 2020-04-14 09:34
Closed by #878

**Closed by Velenir** 2020-04-14 09:34 UTC
Labels: bug, important
