### ISSUE TITLE
Orders are not show

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#455] opened 2020-01-27 09:53 UTC
Reported by @koeppelmann:

I created a bunch of orders directly via the “placeValidFrom” command. Potentially used a token ID that did not exist on rinkeby

![image](https://user-images.githubusercontent.com/2352112/73164660-a43dd380-40f2-11ea-9bae-e56a3f181aef.png)

--------
anxo: Probably is one of these 2:
- Use pagination for loading the orders of the user: The new smart contract version allow to paginate the orders, so you can overcome the limits of gaslimit in a call
- Related to support any token in the interface: #376, #378, #379

**Comment by W3stside** [comment] 2020-01-29 10:51
@anxolin I don't get this one, can you elaborate? Is this Martin messing around with the contracts directly and then checking if the FE supported this in the orders page?

**Comment by anxolin** [comment] 2020-01-29 11:10
>  Is this Martin messing around with the contracts directly and then checking if the FE supported this in the orders page?

Probably :) 

I've got this directly from his feedback in https://docs.google.com/document/d/1WCP3YNnJ6wagRL5ZhdUJ9wcmxoNXCp55jsQCeuiVDqI/edit# (I just made the issue, and added what 2 things I thought could be the cause)

@koeppelmann , is this still happening to you? Can you help us reproduce it?

**Comment by W3stside** [comment] 2020-01-29 13:14
@anxolin i don't see Martin's report in the bug doc

**Comment by alfetopito** [comment] 2020-01-29 16:53
Not sure it's related to the issue or not, but I can already reproduce a use case where pagination is handy.
~I have a couple ~ Actually I deleted my orders because the page was too slow.

Anyway, that's my point. With over 50 expired orders, switching between active/expired takes quite awhile to load.

**Comment by anxolin** [comment] 2020-01-29 17:20
> Not sure it's related to the issue or not

Yep. I also think it can be that @alfetopito!

> @anxolin i don't see Martin's report in the bug doc

David, it was, but I moved here. With all the info that he wrote. Ping him if you need help reproducing, although I believe it's what Leandro suggests. This method was not paginated in the past, now we can paginate to avoid this issues
![image](https://user-images.githubusercontent.com/2352112/73380112-bfac0880-42c3-11ea-9929-ecf149254195.png)

**Comment by alfetopito** [comment] 2020-01-29 18:43
I'll start working on the pagination. Can re-prioritize during next sprint planning but besides the UI (how the pages should look like), the `backend` (interacting with the contract, hooks and so on) logic won't change.

**Comment by anxolin** [comment] 2020-01-30 11:01
Cool! thanks leandro

**Comment by alfetopito** [comment] 2020-02-13 16:49
Pagination have been merged into develop and will be deployed on next release.

Closing for now, feel free to re-open if issue re-appears.

**Closed by alfetopito** 2020-02-13 16:49 UTC
Labels: bug
