### ISSUE TITLE
Add token in the balances page - Manage tokens

### ISSUE THREAD

**Issue by W3stside** [gnosis/dex-react#980] opened 2020-04-30 07:40 UTC
Manage 'em
@Velenir please add more deets here especially with that new discussion on slack today 30.04

In the bottom, a banner ""Not in the list?"

**Comment by W3stside** [comment] 2020-04-30 10:18
`Est: 5`

**Comment by alfetopito** [comment] 2020-05-11 17:19
duplicate of https://github.com/gnosis/dex-react/issues/379

**Closed by alfetopito** 2020-05-11 17:19 UTC
Labels: important
