### ISSUE TITLE
Improve start batch / expire batch

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#1205] opened 2020-07-07 17:51 UTC
## Improve start batch / expire batch

Date picker? batch id 
Proposal + simple impl

It currently uses minutes, that is a bit difficult to use for targeting an specific batch

One idea could be to do the app more batch aware. Probably allowing the user to select a batch.
Ideally also a date (showing UTC time + Local Time?)

This would allow users to schedule their token sales

_Estimation: 2_

**Comment by W3stside** [comment] 2020-07-14 09:26
Current proposal:

![Screenshot from 2020-07-14 11-25-38](https://user-images.githubusercontent.com/21335563/87409117-c950d080-c5c4-11ea-9530-1d8c6d838def.png)

@alfetopito @Velenir @anxolin

**Comment by alfetopito** [comment] 2020-07-14 16:02
Discussion happening on https://gnosisinc.slack.com/archives/CSGLUC1BN/p1594718885008800

@W3stside you could share it with dxdao to get their inputs as well

**Comment by anxolin** [comment] 2020-07-22 11:26
Is this a duplicate of https://github.com/gnosis/dex-react/issues/1205? @W3stside

**Comment by alfetopito** [comment] 2020-07-22 14:31
You mean https://github.com/gnosis/dex-react/issues/1052, #1205 is this issue :)

**Comment by anxolin** [comment] 2020-07-24 11:44
hehehe, yep 😂. It shows above now as closed

**Comment by Velenir** [comment] 2020-08-20 08:10
Tracked in #1269

**Closed** 2020-09-10 12:59 UTC
